services:
  db:
    env_file: .env
    image: mysql:9.4.0
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    env_file: .env
    ports:
      - ${APP_PORT:-8080}:8080
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${IMAGES_BASE_PATH:-./images}:/app/images

  nginx:
    image: nginx:1.29.2
    ports:
      - ${NGINX_PORT:-8082}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${IMAGES_BASE_PATH:-./images}:/var/www/images:ro

volumes:
  db:
