version: "3.8"
services:
  mysql:
    env_file: .env
    image: mysql:9.4.0
    ports:
      - "33062:3306"
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-init db.d/db.sql:ro

  nginx:
    image: nginx:1.29.2
    ports:
      - "8082:80"
      - "444:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./images:/var/www/images
    restart: unless-stopped

volumes:
  mysql_data: